# Generated by Django 3.1.1 on 2022-12-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Busno',
            field=models.IntegerField(help_text='Busno', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='noofseats',
            field=models.IntegerField(),
        ),
    ]
